# products/graphql/queries/products_by_category_with_attributes.graphql
query ProductsByCategoryWithAttributes(
  $slug: String!,
  $first: Int!,
  $after: String,
  $channel: String!,
  $filter: ProductFilterInput,
  $lang: LanguageCodeEnum!
) {
  category(slug: $slug) {
    products(first: $first, after: $after, channel: $channel, filter: $filter) {
      totalCount
      edges {
        node {
          id
          name
          slug
          translation(languageCode: $lang) { name }
          thumbnail { url alt }
          pricing {
            priceRange {
              start {
                gross { amount currency }
              }
            }
            priceRangeUndiscounted {
              start {
                gross { amount currency }
              }
            }
          }
          attributes {
            attribute {
              id
              slug
              name
              translation(languageCode: $lang) { name }
            }
            values {
              id
              slug
              name
              translation(languageCode: $lang) { name }
            }
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}